### ISSUE TITLE
2 identical widgets on one page

### ISSUE THREAD

**Issue by sircovsw** [seriousben/embeddable-react-widget#211]
Hi.
Posted 2 widgets on one page of the site.
The second widget on startup changes the state of both widgets.
How to make each widget have its own state?
Thanks

**Comment by seriousben** [comment]
Were you able to make this work?

**Comment by sircovsw** [comment]
Yes.
I used the widget instance settings incorrectly.
Everything's fine now.
![Screenshot_2](https://user-images.githubusercontent.com/3596745/68863263-0bf19e80-0700-11ea-853c-59476717eaad.jpg)
