### ISSUE TITLE
Tree Shaking / Bundle Size?

### ISSUE THREAD

**Issue by mattrothenberg** [seriousben/embeddable-react-widget#34]
Howdy!

First and foremost, thanks for creating such an amazing library. It's been an absolute breeze developing an embedded widget, thanks to your hard work + documentation!

There's one thing I'd like your advice on – I've noticed my bundle size is **massive** (over 1mb), and I'm looking for ways to optimize. 

For instance, I'm using a handful of these lovely icons https://github.com/carmelopullara/react-feather, and they add several hundred KB to the resulting bundle. I figured Webpack would have "shaken" out the unused icons, but looks like I'm wrong (or have an incorrect understanding of what Webpack is doing).

Any ideas?

**Comment by mattrothenberg** [comment]
Errr, looks like I spoke too soon. There's an active issue about tree-shaking with that particular library 😅 https://github.com/carmelopullara/react-feather/issues/6.

In any event, optimization tips would be greatly appreciated as I try to shave down a few KB here + there before shipping this thing to prime time.

<3

**Comment by seriousben** [comment]
@mattrothenberg AFAIK this is working right now. The issue you linked to for your specific issue does not seem related to any settings in this project. Please let me know if you see problems with how webpack is configured.
