### ISSUE TITLE
Bug: Change webpack.config if you use clean-webpack-plugin@2

### ISSUE THREAD

**Issue by taksenov** [seriousben/embeddable-react-widget#55]
Sorry for my English, it is not ideal. 

I'm using your app and very happy with the functionality, thank you.

But in the clean-webpack-plugin@2 has changed the API:
https://github.com/johnagan/clean-webpack-plugin/releases/tag/v2.0.0
`No configuration is needed for standard usage (cleans webpack's output.path)`

In this line of the webpack.config.js: https://github.com/seriousben/embeddable-react-widget/blob/master/webpack.config.js#L11
You should change the code to this: `new CleanWebpackPlugin(),`

**Comment by seriousben** [comment]
@taksenov I would happy to review code addressing this issue if you have time.

**Comment by seriousben** [comment]
Thanks for opening this issue @taksenov this was fixed in #82
